### ISSUE TITLE
Upgrade to OSX Sierra breaks functionality

### ISSUE THREAD

**Issue by jacobroufa** [gnarf/osx-compose-key#15]
As of this week when I upgraded to Sierra, my compose keys no longer works. Has anyone else using this noticed that issue? What have you done to remedy?

**Comment by gnarf** [comment]
Did you try reinstalling karabiner and the plists? I haven't updated yet myself

**Comment by jacobroufa** [comment]
It appears that tekezo/Karabiner#660 is going to give us issues. I'll check back in with this issue when the one I just referenced is resolved. Thanks @gnarf!

**Comment by oetiker** [comment]
There is an easy solution:
- uninstall karabiner
- install https://github.com/tekezo/Karabiner-Elements
- start karabiner-elements
- map `right_command` to `non_us_backslash`

**Comment by jacobroufa** [comment]
♫┗(＾0＾)┓♫

**Comment by jacobroufa** [comment]
What I mean to say is, this is fantastic @oetiker. I had previously tried Karabiner Elements, to no effect. Now it works wonderfully. Thanks!

**Comment by gnarf** [comment]
Hrm, is there any way you could update the "install" or "readme" to describe how to do this with Elements @jacobroufa ?

**Comment by jacobroufa** [comment]
Sure. I'll open a PR in a bit with both an updated install and readme.

**Comment by domq** [comment]
Unfortunately this only works on keyboards that do *not* have a `non_us_backslash` key. I have a French keyboard ☹ and `non_us_backslash` is actually the @ key.

Previous versions of Karabiner used to be able to  [substitute Ctrl+Shift+F13](http://apple.stackexchange.com/questions/31487/add-compose-key-to-os-x) which besides being impossible to type on a physical keyboard, is basically never assigned a special meaning by apps (unlike plain F13 in e.g. Terminal).

Is there a way to add back the feature of substituting not just one key for another, but to slip in modifier changes as well?

**Comment by fleskesvor** [comment]
It doesn't work on my Scandinavian keyboard either. Configuring `right_option` as the compose key in Karabiner Elements as described in the readme only inserts an apostrophe (`'`) when pressed.
