### ISSUE TITLE
Not able to use compose key in iTerm2

### ISSUE THREAD

**Issue by ehamberg** [gnarf/osx-compose-key#2]
The `shift-ctrl-F13` mapping does not seem to work in iTerm2. It seems to actually send that key press “raw” and not wait for a compose sequence to be completed. I verified this by using `ctrl-v` in vim's insert mode to insert “literally” and observing that `<F13>` was inserted.

By changing the compose key to `§`, I got it working, so the issue could be the use of a special key (with modifiers). Here's the relevant section from Karabiner's `private.xml`¹:

```
<item>
  <name>Send § for Right Option</name>
  <identifier>private.send_section_sign_for_ropt</identifier>
  <autogen>--KeyToKey-- KeyCode::OPTION_R,
      KeyCode::DANISH_DOLLAR
  </autogen>
</item>
```

[1] “Danish Dollar”‽

**Comment by gnarf** [comment]
Could you send this as a PR with both files uploaded? :+1: :beers:

**Comment by gnarf** [comment]
....updated... Phone autocorrect
