### ISSUE TITLE
incompatibility with iTerm 2

### ISSUE THREAD

**Issue by rothskeller** [gnarf/osx-compose-key#22]
osx-compose-key seems to be working correctly in most of my applications (and thank you!).  But it does not work correctly in iTerm 2.  For example, when I type [Compose]12 in most applications, I get ½.  But when I type it in iTerm 2, I get §1½.

Of course I don't hold osx-compose-key responsible for compatibility with every other application on the planet, but I thought you might want to know.

**Comment by bwbaugh** [comment]
FWIW, this is working for me in iterm2 (Build 3.0.15). I use Right-⌘ as my Compose Key (since I want to continue using Right-⌥).

As an aside, I noticed that the standard OS X ⌥-shortcuts (as in `⌥ + , = ≤`) only worked in iterm2 when Right-⌥ was used, as iterm2 seems to take / override Left-⌥.

**Comment by bwbaugh** [comment]
@rothskeller By any chance, are you holding down the Compose Key? When I hold down the Compose Key I get "§§§§§§§…". If you happen to be holding it down, know that you can also tap it very briefly and continue to type the remaining of the combination. 🤞

**Comment by rothskeller** [comment]
I was using an old version of iTerm 2.  After upgrade, it works fine for me too.  (No, I wasn't holding down the Compose key.)
